import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        />
      </head>
    
      <body className="abc-website without-banner lang-eng">{children}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

      {/* <script defer="" src="https://launchpad.privacymanager.io/latest/launchpad.bundle.js"></script><script async="" src="https://platform-api.sharethis.com/panorama.js"></script><iframe id="pxcelframe" title="pxcelframe" src="//t.sharethis.com/a/t_.htm?ver=1.1183.23362&amp;cid=c010&amp;cls=B#cid=c010&amp;cls=B&amp;dmn=lifeinsurance.adityabirlacapital.com&amp;rnd=1690525589363&amp;tt=t.dhj&amp;dhjLcy=385&amp;lbl=pxcel&amp;flbl=pxcel&amp;ll=d&amp;ver=1.1183.23362&amp;ell=d&amp;cck=__stid&amp;pn=%2Farticles%2Fterm-insurance%2Fterm-insurance-guide-for-young-professionals&amp;qs=na&amp;rdn=lifeinsurance.adityabirlacapital.com&amp;rpn=%2Farticles%2Fterm-insurance%2Fterm-insurance-guide-for-young-professionals&amp;rqs=na&amp;cc=IN&amp;cont=AS&amp;ipaddr=" style={{display: 'none'}}></iframe><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-L579HEBE2L&amp;l=dataLayer&amp;cx=c" nonce=""></script><script async="" id="mfilterit-visit-tag" src="https://script.mfilterit.net/v3/v/client/web.adityabirlacapitalfmp.cpv.js"></script><script src="https://connect.facebook.net/signals/config/616461893796405?v=next&amp;r=canary" async=""></script><script src="https://connect.facebook.net/signals/config/563252102341679?v=next&amp;r=canary" async=""></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js" nonce=""></script><script async="" src="https://buttons-config.sharethis.com/js/5f619fde43839f001976529f.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-MLFN639"></script><script nonce="" type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5f619fde43839f001976529f&amp;product=custom-share-buttons" defer=""></script>
      <script defer src="https://https-lifeinsurance-adityabirlacapital-com.disqus.com/embed.js" data-timestamp="1690525588430"></script>
      <script src="https://c.disquscdn.com/next/embed/alfie_v4.63f1ab6d6b9d5807dc0c94ef3fe0b851.js" async="" charSet="UTF-8"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script><script src="https://launchpad-wrapper.privacymanager.io/876583a8-81cb-4d63-9d57-50a52a0bd20a/launchpad-liveramp.js" defer="" charSet="UTF-8"></script> */}
      </body>
    </html>
  )
}
